### ISSUE TITLE
Wrong maven repo

### ISSUE THREAD

**Issue by gamerover98** [TozyMC/commands-api#1]
You must add the jcenter repository into a pom if you want to find your resource.
**repository**:
  id: jcentre
  name: jcenter
  URL: https://jcenter.bintray.com

And you must set as provided the org.jetbrains.annotations-java5 dependency from your pom, to prevent issues during compiling.

> https://prnt.sc/vepywy

**Comment by TozyMC** [comment]
Ok, thanks for your issue. I forget adding provided scope to pom file. I will fix in next update, it will coming soon.
