### ISSUE TITLE
[BUG] Wrong no permission message

### ISSUE THREAD

**Issue by gamerover98** [TozyMC/commands-api#3]
**Description**
The no-permission message hasn't colour transition.
https://i.imgur.com/ZZMrFx8.png

My command code: https://github.com/gamerover98/NoBlackSky/blob/master/src/main/java/it/gamerover/nbs/command/PluginCommand.java

- Server Version: [1.15.2]
- Server Type: [PaperMC]

**Comment by TozyMC** [comment]
Ok, default messages hasn't color. The constructor of the `CommomMessage` class is not called. I will fix it soon.

**Comment by TozyMC** [comment]
Your issue is fixed and patched in release [`v2.0`](https://github.com/TozyMC/commands-api/releases/tag/v2.0).
