### ISSUE TITLE
Update to 1.2

### ISSUE THREAD

**Issue by gamerover98** [TozyMC/commands-api#4]
Hi, can you update your maven to the latest committed version? I've tried the chat colours and it and works.

**Comment by TozyMC** [comment]
Ok, but not now. New features are evolving and take time. Temporarily, you can set custom messages via `CommomMessage` to fix it. See javadoc [here](https://www.javadoc.io/doc/xyz.tozymc.spigot/commands-api/latest/xyz/tozymc/spigot/api/command/util/CommonMessage.html). Thanks for your issue.

**Comment by TozyMC** [comment]
Ok, it is update to version 2.0
