### ISSUE TITLE
Can't use commands-api:2.1 due to not being able to resolve spigot-api

### ISSUE THREAD

**Issue by murl-digital** [TozyMC/commands-api#7]
**Description**
When attempting to use the latest version of command-api (2.1), gradle is unable to resolve spigot-api.

**Log console**
`Could not find spigot-api-1.16.5-R0.1-SNAPSHOT.jar (org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT:20210515.001736-77).
Searched in the following locations:
    https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.16.5-R0.1-SNAPSHOT/spigot-api-1.16.5-R0.1-20210515.001736-77.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

**Additional Information:**

- N/A, i can provide more upon request

**Comment by TozyMC** [comment]
Ok,  i will check and fix they soon.

**Comment by TozyMC** [comment]
> **Description** When attempting to use the latest version of command-api (2.1), gradle is unable to resolve spigot-api.
> 
> **Log console** `Could not find spigot-api-1.16.5-R0.1-SNAPSHOT.jar (org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT:20210515.001736-77). Searched in the following locations: https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.16.5-R0.1-SNAPSHOT/spigot-api-1.16.5-R0.1-20210515.001736-77.jar
> 
> Possible solution:
> 
> * Declare repository providing the artifact, see the documentation at [https://docs.gradle.org/current/userguide/declaring_repositories.html`](https://docs.gradle.org/current/userguide/declaring_repositories.html%60)
> 
> **Additional Information:**
> 
> * N/A, i can provide more upon request

It's fixed, please check it again. Thanks for you issue.

**Comment by murl-digital** [comment]
yep, this seems to be resolved. thank you!
